#server configuration
server:
  port: 8080
  servlet:
    context-path: /api/

#Profile configuration
spring:
  application:
  name: inTrack
  profiles:
    active:
      - dev
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.xml

  #Database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/inTrack
    username: inTrack_user
    password: inTrack
    hikari:
      pool-name: inTrack-dev
      connection-timeout: 30000
      minimum-idle: 10
      idle-timeout: 6000000
      max-lifetime: 1800000
      maximum-pool-size: 25
      register-mbeans: true
  jpa:
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect
  logging:
    level:
      org.springframework: DEBUG

#Jwt configuration
jwt-secret: 2F3C44BB8BA7477DA55734CF38258E455FC2F559C46F484CAC29247D6B9B74D58C8E8CD9457F4CDAAAE97F4112AA5F01E78B6984A43C49CA909BD5BC245D0AF461AAF9E126904E90A80E6997B1C16086
jwt-token-validity: 240 #In hour